///GET Users List Request Actions
export const GET_USERS_LIST_START = "GET_USERS_LIST_START";
export const GET_USERS_LIST_SUCCESS = "GET_USERS_LIST_SUCCESS";
export const GET_USERS_LIST_ERROR = "GET_USERS_LIST_ERROR";
export const GET_USERS_LIST_FINISH = "GET_USERS_LIST_FINISH";

///GET User Request Actions
export const GET_USER_LIST_START = "GET_USER_LIST_START";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const GET_USER_LIST_ERROR = "GET_USER_LIST_ERROR";
export const GET_USER_LIST_FINISH = "GET_USER_LIST_FINISH";

//UPDATE User Request Actions
export const UPDATE_USER_LIST_START = "UPDATE_USER_LIST_START";
export const UPDATE_USER_LIST_SUCCESS = "UPDATE_USER_LIST_SUCCESS";
export const UPDATE_USER_LIST_ERROR = "UPDATE_USER_LIST_ERROR";
export const UPDATE_USER_LIST_FINISH = "UPDATE_USER_LIST_FINISH";

//CREATE User Request Actions
export const CREATE_USER_LIST_START = "CREATE_USER_LIST_START";
export const CREATE_USER_LIST_SUCCESS = "CREATE_USER_LIST_SUCCESS";
export const CREATE_USER_LIST_ERROR = "CREATE_USER_LIST_ERROR";
export const CREATE_USER_LIST_FINISH = "CREATE_USER_LIST_FINISH";

//DELETE User Request Actions
export const DELETE_USER_LIST_START = "DELETE_USER_LIST_START";
export const DELETE_USER_LIST_SUCCESS = "DELETE_USER_LIST_SUCCESS";
export const DELETE_USER_LIST_ERROR = "DELETE_USER_LIST_ERROR";
export const DELETE_USER_LIST_FINISH = "DELETE_USER_LIST_FINISH";



